CREATE DATABASE IF NOT EXISTS alunos;
USE alunos;

CREATE TABLE IF NOT EXISTS alunos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    matricula VARCHAR(50) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    nome VARCHAR(50) NOT NULL
);